In [ ]:
import pandas as pd

In [ ]:
a=pd.read_csv("../input/novel-corona-virus-2019-dataset/covid_19_data.csv")
a.head()

In [ ]:
type(a["ObservationDate"][0])   # here observation date is in string we have to convert into date.

In [ ]:
a.info()

In [ ]:
a["ObservationDate"]=pd.to_datetime(a["ObservationDate"])  #  string is converted into date format
a["Last Update  "]=pd.to_datetime(a["Last Update"])

In [ ]:
a.info()

# Mask Filtering

To get rows of india we use mask filtering .

In [ ]:
a["Country/Region"]=="India"
Mask1=a["Country/Region"]=="India"
Mask1

In [ ]:
a[Mask1]   # it returns records having india in country.

In [ ]:
Mask2=a["ObservationDate"]=="2021-05-21"

In [ ]:
a[Mask2]

In [ ]:
b=a[Mask1&Mask2]
b

In [ ]:
b.sort_values("Confirmed",ascending=False)   # it sorts the values based on the confirmed column in descending order.

**isin() method**


It is used to check presence of values.Compares two values.

In [ ]:
mask=a["Country/Region"].isin(["India","Japan"])   # it returns the boolean value  true when country is india or japan otherwise false
mask

In [ ]:
a[mask]

**with isin() method,we can compare multiple values.**

**without isin() method,we need to logical operator.**

**without isin() method**

In [ ]:
a=pd.read_csv("../input/novel-corona-virus-2019-dataset/covid_19_data.csv")
a

In [ ]:
mask1=a["Country/Region"]=="India"
mask1

In [ ]:
mask2=a["Country/Region"]=="Japan"
mask2

In [ ]:
a[mask1|mask2]    # without isin() method we need to use logical operator to compare multiple values.

**Null Filtering**

isnull()/isna() methods returns  null records means it returns true when there is null present in record.

notnull() returns not null records means records with no null value.

In [ ]:
a=pd.read_csv("../input/novel-corona-virus-2019-dataset/covid_19_data.csv")
a

In [ ]:
a.info()

In [ ]:
mask=a["Province/State"].isnull()   # isnull() returns true when there is null record otherwise false
mask

In [ ]:
a[mask]

In [ ]:
mask=a["Province/State"].notnull()   # notnull() returns true when there is  no null record otherwise false
mask

In [ ]:
a[mask]

# between() method

**it is used to specify the  continuous range(lower value,upper value both are inclusive).whatever the data present in the range,it is filtered based on that.**

In [ ]:
mask=a["Confirmed"].between(20,50)  # it returns records where confirmed cases between 20 and 50
mask

In [ ]:
a[mask]

# Find duplicates **using duplicated() method**.


**It is used to find dupicated records.**

In [ ]:
a={
    "student":["pavan","sumanth","pavan","sai","pavan"],
    "age":[18,21,22,12,18],
    "marks":[25,22,41,22,25]
}

In [ ]:
df=pd.DataFrame(a)
df

In [ ]:
mask=df.duplicated()
mask# it returns true when whole record is repeated otherwise false. Here sth record is repeated same as first oone so true.

In [ ]:
df[mask]

In [ ]:
mask=df["student"].duplicated()
mask                           # it is different from previous one.it finds out duplicates only in name column and returns true if duplicate is found.

In [ ]:
df[mask]   # here 2 and 4 uplicated in names columns so those records are returned.

**To find out duplicate records based on subset of columns we use subset attribute.**

In [ ]:
mask=df.duplicated(subset=["student","age","marks"])  # iit returns duplkicate record based on the name,marks,age column
mask

In [ ]:
df[mask]

**Treating Duplicates using drop_duplicates() method**

In [2]:
import pandas as pd 
a={
    "student":["pavan","sumanth","pavan","sai","pavan"],
    "age":[18,21,22,12,18],
    "marks":[25,22,41,22,25]
}
df=pd.DataFrame(a)
df

   student  age  marks
0    pavan   18     25
1  sumanth   21     22
2    pavan   22     41
3      sai   12     22
4    pavan   18     25

In [ ]:
mask=df["student"].drop_duplicates()
mask# it drops duplicates in the names column and remove the duplicates.

In [ ]:
df.drop_duplicates(subset=["student","age","marks"])  # only 5th row is repeated it is same as ist row so it is removed but 3rd row is not removed beacuse only name is repeated but not marks and age.we specified all three conditions.so it is not removed.

**Distinct Counts using unique() method**

It is used to return list of distinct unique  values in a column

In [ ]:
a=pd.read_csv("../input/novel-corona-virus-2019-dataset/covid_19_data.csv")
a

In [ ]:
a["Country/Region"].unique()  # used to find unique values in country column

In [ ]:
a["Country/Region"].nunique()  #used to find  no of unique values in country column

**Customisation Index**

we can set our own index using index_col in read_csv method.

other way is we can set the index using set_index method.

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv")
a

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col=["Job_Role"])
a

In [ ]:
a.reset_index()   # we can reset index to intial position using reset_index() method

**set_index() method.**

In [ ]:
a.set_index("Company")

In [ ]:
a=a.reset_index()

In [ ]:
a

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv")
a.set_index("Job_Role",drop=False,inplace=True)  # here job role will be  deleted as we set new index.so it should not be in that way.we need to use drop attribute in orde to avoid it.
a# set index as job_Role

In [ ]:
a.set_index("Company",inplace=True)

To append new index to alreday existing index we use append attribute set_index() method.

In [ ]:
a.set_index("Location",append=True)    # it appends the index location to company iondex.

**we need to use reset_index() method if we have to use set_index() method consecutively.**

# loc used to  access the rows or group of rows  using our own index in the dataframe.

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv")
a

In [ ]:
a.loc["Data Scientist"]

In [ ]:
a.loc[".Net Developer"]  # it gives error as our index is not jobrole is is number

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col=["Job_Role"])
a

In [ ]:
a.loc["Data Scientist"]  # it return rows of datscientist index

**To access the two index values we specify inbdex in the nested list**

In [ ]:
a.loc[["Data Scientist","Senior Data Scientist"]]   # it return rows of data scientist and senior data scientist index.

In [ ]:
a.head()

**Slicing**

In [ ]:
a.loc["Applied Data Scientist / ML Senior Engineer (Python / SQL)":"Data Scientist"]  #here multiple key values are present so it get confused so we have error.

# **iloc used to  access the rows or group of rows  using numeric index in the dataframe.**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col=["Job_Role"])
a

In [ ]:
a.iloc[0]        # used to get row of index 0

In [ ]:
a.iloc[[0,5,10]]   # used to return 0,5,10 rows.

**slicing**

In [ ]:
a[0:100:10]   # here 100 is exclusive

In [ ]:
a.tail()

In [ ]:
a.loc["Tech Lead / POD Lead":"Tech Lead - Azure"]  # it returns rows from two specified index

In [ ]:
a.tail()

**To access the value at specified row and specified column**   loc[index name,column name]

In [ ]:
a.loc["Tech Lead/Architect ( Contractual )","Company"]  # it returns the value of "Tech Lead/Architect ( Contractual )" index and "Company" column

In [ ]:
a.loc["Senior Data Scientist","Company"]  # returns rows with senior data scienist index and company column

In [ ]:
a.loc["Senior Data Scientist",["Company","Location"]]  #returns rows with senior data scienist row and company,location column

In [ ]:
a.loc[:,["Company","Location"]]  # retrn all rows with specified columns loc[rows name,column name]

# **Updating the values in dataframe using loc**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

**To rename single column**

In [ ]:
a.loc["Data Scientist","comapany"]="HP"  # it changed the valueof data scientist index and company column.
a

**To rename multiple columns**

In [ ]:
a.loc["Data Scientist",["comapany","Location"]]=["HP","Bengaluru"]
a

**Rename all Bangalore to Bengaluru**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

In [ ]:
mask=a.loc[:,"Location"].isin(["Bangalore","Bangalore/Bengaluru"])  # to find out rows that contain bangalore/bengaluru
mask

In [ ]:
a[mask]  # It return all rows that contain Bangalore/Bengaluru

**we need to renmae the Bangalore/bengaluru to bengaluru**

In [ ]:
a[mask].loc[:,"Location"]="Bengaluru"  # here a[mask] is new datframe but we ned to apply operation on original one that is a.

In [ ]:
a.loc[mask,"Location"]="Bengaluru"   # it renames the location to bengaluru in mask rows

In [ ]:
a.loc[mask]

**Rename**

* we can reneme index or column by two ways
* mapper+axis
* index

**Index Rename using mapper and axis**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

**we convert the senor data scientist to senior data analyst an data scientist to data analyst using mapper class and axis.**

In [ ]:
a.rename(mapper={"Senior Data Scientist":"Senior Data Analyst",
                "Data Scientist	":"Data Analyst"},axis=0,inplace=True)           # it rename all the specified indexes.

In [ ]:
a

**Index Rename using index**

In [ ]:
a.rename(index={"Senior Data Analyst":"Senior Data Scientist",
                "Data Analyst":"Data Scientist"},inplace=True)

In [ ]:
a

**Column renaming**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

**using mapper and axis**

In [ ]:
a.rename(mapper={"Company":"Firm",
                "Location":"Place"},axis=1,inplace=True)  # we have renamed cpmapany column top firm and location to place and used axis attribute tos specify it is related to column.

In [ ]:
a

using column attribute

In [ ]:
a.rename(columns={"Firm":"Company",
                "Place":"Location"},inplace=True)

In [ ]:
a

**Delete rows and columns**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

In [3]:
a.describe()

AttributeError: 'dict' object has no attribute 'describe'

**Drop rows**

In [ ]:
a.drop(labels="Senior Data Scientist",inplace=True)  # it removes rows that have data scientist index

In [ ]:
a.describe()

**Drop Columns**

In [ ]:
a.drop(labels="Company",axis=1)   # it drops column company.

In [ ]:
l=a.pop("Location")   # pop funnction alo used to drop columns and it also stores deleted columns.

In [ ]:
l

In [ ]:
a

In [ ]:
del a["Job Experience"]   # it deletes jobs column permanently

In [ ]:
a

**Random sample**


In some situations we do not need entire data we can take sample of data from whole data using sample method

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

In [ ]:
a.sample(n=4)  # it returns any four rows from whole data.

In [ ]:
a.sample(n=2,axis=1)  #it returns any two columns

In [ ]:
a.sample(frac=0.1)  # frac is used to specify how much data to smaple from whole data here given 0.1 means 10% of the whole dat i.e 1200 rows

**Find Smallest and Largest value.**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

In [ ]:
a.describe()

In [ ]:
import numpy as np

In [ ]:
a["Salary"]=np.random.randint(300000,4000000,size=12000)  # we added column salary into a dataframe

In [ ]:
a

In [ ]:
a.sort_values("Salary",ascending=False).head(3)

In [ ]:
a["Salary"].nlargest(3)   # it gives 3 largest values

In [ ]:
a["Salary"].nsmallest(3)   # it gives sammllest values

# Where ()  method 

It is like similar to mask filtering.used to replace  false values with null values or any otrher value

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

In [ ]:
mask=a["Location"]=="Bangalore/Bengaluru"
mask

In [ ]:
a[mask]   # mask filtering treturns only records that have true values.

#  Difference between Mask filtering and where condition
 
**Mask filtering returns only true records.
but where condition returns true records as well as it  return records that are false  but it will fill those details with null values.**

In [ ]:
a.where(a["Location"]=="Bangalore/Bengaluru")  # it returns true records and also return records that do not have loaction specified but it wiill those details with null values.

In [ ]:
import numpy as np
a=np.random.randint(10,200,(4,4))
a

In [ ]:
df=pd.DataFrame(np.random.randint(10,200,(4,4)),index=["Pavan","sai","sumanth","Vinay"],columns=["t1","t2","t3","t4"])
df

Where() replaces false values with specified values given by user.

In [ ]:
df>60

In [ ]:
df.where(df>60,"ABC",inplace=True)  # it is not supported beecause we have string type in our data.
df

In [ ]:
df=pd.DataFrame(np.random.randint(10,200,(4,4)),index=["Pavan","sai","sumanth","Vinay"],columns=["t1","t2","t3","t4"])
df

In [ ]:
df.where(df>120,"ABC",inplace=True)   #vit replaces the values taht do not satisfy condition  with ABC value
df

In [ ]:
df=pd.DataFrame(np.random.randint(10,200,(4,4)),index=["Pavan","sai","sumanth","Vinay"],columns=["t1","t2","t3","t4"])
df

In [ ]:
df.where(df<100,lambda x:x+10,inplace=True)
df

In [ ]:
df.where(lambda x:x<100,"B",inplace=True)
df

# query() method  query rows based on boolean expression.

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

In [ ]:
a.query("Job_Role=='Data Scientist'")   # return rows where jobrole is datascientist.

We can also replace column names

In [ ]:
a.columns

In [ ]:
a.columns=[i.replace(" ","_") for i in a.columns]
a.columns

In [ ]:
a.query("Job_Role=='Data Scientist' & Location=='Bengaluru'")

**apply() function used to  perform transformation on  group of column values.**

In [ ]:
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a

In [ ]:
import numpy as np
a["Salary"]=np.random.randint(100000,500000,12000)
a

In [ ]:
a["Salary"]=a["Salary"].apply(lambda x: "Rs" + str(x))   # apply function on all values of salary column.
a

In [ ]:
import numpy as np
a=pd.read_csv("../input/data-science-jobs-in-india/naukri_data_science_jobs_india.csv",index_col="Job_Role")
a["Salary"]=np.random.randint(100000,500000,12000)
a

In [ ]:
def fun(num):
    if num<250000:
        return 'A'
    else:
        return 'B'

In [ ]:
a["band"]=a["Salary"].apply(fun)
a

In [ ]:
a["band"].value_counts()

**To apply a function to rows**

In [ ]:
def fun(x):
    loc=x["Location"]
    j=x["Job Experience"]
    if loc in ["Bangalore/Bengaluru"] and j=="3-6":
        return "YES"
    else:
        return "NO"

In [ ]:
a["apply or not"]=a.apply(fun)   # we nned to specify axis.

In [ ]:
a["apply or not"]=a.apply(fun,axis=1) 
a

In [ ]:
a["apply or not"].value_counts()

In [ ]:
a=pd.read_csv("../input/employees-evaluation-for-promotion/employee_promotion.csv")
a.head()

In [ ]:
a.info()

In [ ]:
a["gender"]=a["gender"].astype("category")

In [ ]:
a["recruitment_channel"].nunique()

In [ ]:
a["recruitment_channel"]=a["recruitment_channel"].astype("category")

In [ ]:
a["previous_year_rating"].unique()

In [ ]:
a["previous_year_rating"]=a["previous_year_rating"].astype("category")
a.info()

In [ ]:
a["gender"].captialize()  # we get an error that series do not have captilaize function.so when we need  operation on series we need to use  series.str,function to solve this problem.

In [ ]:
a["gender"]=a["gender"].str.capitalize()
a["gender"]

In [ ]:
a

To replace values in region columns  nd title case the region column.

**Method Chaining**

**one method apply one after another**

In [ ]:
a=pd.read_csv("../input/employees-evaluation-for-promotion/employee_promotion.csv")
a["region"]=a["region"].str.replace("_"," ").str.title()
a["region"]

In [ ]:
a

In [ ]:
mask=a["education"].str.contains("Master")
mask

In [ ]:
a[mask]   # we get error because education has null values so we need to fill it.

In [ ]:
mask=a["education"].fillna("others").str.contains("Master")
mask

In [ ]:
a[mask]

**Index formating and column formating(rename)**

In [ ]:
a=pd.read_csv("../input/employees-evaluation-for-promotion/employee_promotion.csv",index_col="department")

In [ ]:
a.columns

In [ ]:
a.columns.str.replace("_"," ").str.title()

In [ ]:
a.index

In [ ]:
a.index.str.replace("&","and").str.title()

**Multi Hierarchy index**

In [ ]:
a=pd.read_csv("../input/bigbasket-entire-product-list-28k-datapoints/BigBasket Products.csv")
a

In [ ]:
a=pd.read_csv("../input/bigbasket-entire-product-list-28k-datapoints/BigBasket Products.csv",usecols=["category","sub_category","product","rating"])
a

In [ ]:
a.set_index(["category","sub_category"])

**It is good practice to have least unique colum in parent hierarchy.
multiple rows can be clubbed**

**We can have n number of levels in index.Here we have 3 indexes.**

In [ ]:
a.set_index(["category","sub_category","product"])

In [ ]:
a=pd.read_csv("../input/bigbasket-entire-product-list-28k-datapoints/BigBasket Products.csv",usecols=["category","sub_category","product","rating"])
a

In [ ]:
a=pd.read_csv("../input/bigbasket-entire-product-list-28k-datapoints/BigBasket Products.csv",usecols=["category","sub_category","product","rating"],index_col=["category","sub_category"])
a

Fetch the index

In [ ]:
a.index

In [ ]:
a.index.names

**Fetch index using get_level values**

In [ ]:
a.index.get_level_values(0)  # it gives indexex of the first level that is category

In [ ]:
a.index.get_level_values("sub_category")  # we can specify level number or level name

**changing index name**

In [ ]:
a.index.names

In [ ]:
a.index.names=["category","sub category"]   # we have changed the index names
a.index.names

In [ ]:
a.index.names[0]="cat"

**set_names() method**

we can set the index or multiindex name using set_names() method.

In [ ]:
a.index.set_names(["cat","sub_cat"])

**We can change one index name using level attribute of set_names() method.**

In [ ]:
a.index.set_names("category",level=0,inplace=True)
a.index

In [ ]:
a

# sort index

In [ ]:
a.sort_index()   # sort index hierarchially first category and sub category

In [ ]:
a.sort_index(ascending=[False,True])

In [ ]:
a.sort_index(ascending=False,level="category")

**Data Extraction**

In [ ]:
a.loc["Baby Care"]  # we can pass one index in multi index datframe.

**In multi index,enclose indexex in tuple and columns in list.**

In [ ]:
a.loc["Baby Care","product"]   # returns rows with baby care index and products column

In [ ]:
a.loc[("Baby Care","Baby Accessories"),["product","rating"]]    # here we specified two index columns in tuple and columns in list.